modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"
[[mods]] #mandatory
modId="fastfooddelight" #mandatory
version="1.20.1-1.0.0" #mandatory
displayName="FastFood Delight" #mandatory
logoFile="logo.png" #optional
logoBlur=false
credits="vectorwing" #optional
authors="Akaneo" #optional
description="A lightweight fast food expansion for Minecraft!"
itemIcon="fastfooddelight:french_fries"
configBackground="minecraft:textures/block/bricks.png"

[[dependencies.fastfooddelight]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.fastfooddelight]]
modId = "farmersdelight"
mandatory = false
versionRange = "[1.20.1-1.2.4,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.fastfooddelight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
